import 'package:vitalingu/language/language.dart';

class LanguageRegistry {
  static final List<Language>_languagePromptMap = [
    const Language(
      bcp47Code: "en-US",
      nativeLanguageName: "English",
      voices: voicesEnglish,
    ),
    const Language(
      bcp47Code: "de-DE",
      nativeLanguageName: "Deutsch",
      voices: voicesGerman,
    ),
    const Language(
      bcp47Code: "es-MX",
      nativeLanguageName: "Español",
      voices: voicesSpanish,
    ),
  ];

  static List<Language> get languages => List.unmodifiable(_languagePromptMap);
  
  static Language? getLanguageByCode(String bcp47Code) {
    try {
      return _languagePromptMap.firstWhere((lang) => lang.bcp47Code == bcp47Code);
    } catch (e) {
      return null;
    }
  }


}
const List<String> voicesSpanish = [
  'es-AR-ElenaNeural',
  'es-AR-TomasNeural',
  'es-BO-SofiaNeural',
  'es-BO-MarceloNeural',
  'es-CL-CatalinaNeural',
  'es-CL-LorenzoNeural',
  'es-CO-SalomeNeural',
  'es-CO-GonzaloNeural',
  'es-CR-MariaNeural',
  'es-CR-JuanNeural',
  'es-CU-BelkysNeural',
  'es-CU-ManuelNeural',
  'es-DO-RamonaNeural',
  'es-DO-EmilioNeural',
  'es-EC-AndreaNeural',
  'es-EC-LuisNeural',
  'es-ES-ElviraNeural',
  'es-ES-AlvaroNeural',
  'es-ES-ArabellaMultilingualNeural4',
  'es-ES-IsidoraMultilingualNeural4',
  'es-ES-TristanMultilingualNeural4',
  'es-ES-XimenaMultilingualNeural4',
  'es-ES-AbrilNeural',
  'es-ES-ArnauNeural',
  'es-ES-DarioNeural',
  'es-ES-EliasNeural',
  'es-ES-EstrellaNeural',
  'es-ES-IreneNeural',
  'es-ES-LaiaNeural',
  'es-ES-LiaNeural',
  'es-ES-NilNeural',
  'es-ES-SaulNeural',
  'es-ES-TeoNeural',
  'es-ES-TrianaNeural',
  'es-ES-VeraNeural',
  'es-ES-XimenaNeural',
  'es-ES-Tristan:DragonHDLatestNeural',
  'es-ES-Ximena:DragonHDLatestNeural',
  'es-GQ-TeresaNeural',
  'es-GQ-JavierNeural',
  'es-GT-MartaNeural',
  'es-GT-AndresNeural',
  'es-HN-KarlaNeural',
  'es-HN-CarlosNeural',
  'es-MX-DaliaNeural',
  'es-MX-JorgeNeural',
  'es-MX-DaliaMultilingualNeural4',
  'es-MX-JorgeMultilingualNeural4',
  'es-MX-BeatrizNeural',
  'es-MX-CandelaNeural',
  'es-MX-CarlotaNeural',
  'es-MX-CecilioNeural',
  'es-MX-GerardoNeural',
  'es-MX-LarissaNeural',
  'es-MX-LibertoNeural',
  'es-MX-LucianoNeural',
  'es-MX-MarinaNeural',
  'es-MX-NuriaNeural',
  'es-MX-PelayoNeural',
  'es-MX-RenataNeural',
  'es-MX-YagoNeural',
  'es-NI-YolandaNeural',
  'es-NI-FedericoNeural',
  'es-PA-MargaritaNeural',
  'es-PA-RobertoNeural',
  'es-PE-CamilaNeural',
  'es-PE-AlexNeural',
  'es-PR-KarinaNeural',
  'es-PR-VictorNeural',
  'es-PY-TaniaNeural',
  'es-PY-MarioNeural',
  'es-SV-LorenaNeural',
  'es-SV-RodrigoNeural',
  'es-US-PalomaNeural',
  'es-US-AlonsoNeural',
  'es-UY-ValentinaNeural',
  'es-UY-MateoNeural',
  'es-VE-PaolaNeural',
  'es-VE-SebastianNeural',
];

const List<String> voicesGerman = [
  'de-AT-IngridNeural',
  'de-AT-JonasNeural',
  'de-CH-LeniNeural',
  'de-CH-JanNeural',
  'de-DE-KatjaNeural',
  'de-DE-ConradNeural',
  'de-DE-SeraphinaMultilingualNeural4',
  'de-DE-FlorianMultilingualNeural4',
  'de-DE-AmalaNeural',
  'de-DE-BerndNeural',
  'de-DE-ChristophNeural',
  'de-DE-ElkeNeural',
  'de-DE-GiselaNeural',
  'de-DE-KasperNeural',
  'de-DE-KillianNeural',
  'de-DE-KlarissaNeural',
  'de-DE-KlausNeural',
  'de-DE-LouisaNeural',
  'de-DE-MajaNeural',
  'de-DE-RalfNeural',
  'de-DE-TanjaNeural',
  'de-DE-Florian:DragonHDLatestNeural',
  'de-DE-Seraphina:DragonHDLatestNeural',
];

const List<String> voicesEnglish = [
  'en-AU-NatashaNeural',
  'en-AU-WilliamNeural',
  'en-AU-WilliamMultilingualNeural4',
  'en-AU-AnnetteNeural',
  'en-AU-CarlyNeural',
  'en-AU-DarrenNeural',
  'en-AU-DuncanNeural',
  'en-AU-ElsieNeural',
  'en-AU-FreyaNeural',
  'en-AU-JoanneNeural',
  'en-AU-KenNeural',
  'en-AU-KimNeural',
  'en-AU-NeilNeural',
  'en-AU-TimNeural',
  'en-AU-TinaNeural',
  'en-CA-ClaraNeural',
  'en-CA-LiamNeural',
  'en-GB-SoniaNeural',
  'en-GB-RyanNeural',
  'en-GB-LibbyNeural',
  'en-GB-AdaMultilingualNeural4',
  'en-GB-OllieMultilingualNeural4',
  'en-GB-AbbiNeural',
  'en-GB-AlfieNeural',
  'en-GB-BellaNeural',
  'en-GB-ElliotNeural',
  'en-GB-EthanNeural',
  'en-GB-HollieNeural',
  'en-GB-MaisieNeural',
  'en-GB-NoahNeural',
  'en-GB-OliverNeural',
  'en-GB-OliviaNeural',
  'en-GB-ThomasNeural',
  'en-HK-YanNeural',
  'en-HK-SamNeural',
  'en-IE-EmilyNeural',
  'en-IE-ConnorNeural',
  'en-IN-AartiIndicNeural',
  'en-IN-ArjunIndicNeural',
  'en-IN-NeerjaIndicNeural',
  'en-IN-PrabhatIndicNeural',
  'en-IN-AaravNeural',
  'en-IN-AashiNeural',
  'en-IN-AartiNeural',
  'en-IN-ArjunNeural',
  'en-IN-AnanyaNeural',
  'en-IN-KavyaNeural',
  'en-IN-KunalNeural',
  'en-IN-NeerjaNeural',
  'en-IN-PrabhatNeural',
  'en-IN-RehaanNeural',
  'en-KE-AsiliaNeural',
  'en-KE-ChilembaNeural',
  'en-NG-EzinneNeural',
  'en-NG-AbeoNeural',
  'en-NZ-MollyNeural',
  'en-NZ-MitchellNeural',
  'en-PH-RosaNeural',
  'en-PH-JamesNeural',
  'en-SG-LunaNeural',
  'en-SG-WayneNeural',
  'en-TZ-ImaniNeural',
  'en-TZ-ElimuNeural',
  'en-US-AvaMultilingualNeural4',
  'en-US-AndrewMultilingualNeural4',
  'en-US-EmmaMultilingualNeural4',
  'en-US-AlloyTurboMultilingualNeural4',
  'en-US-EchoTurboMultilingualNeural4',
  'en-US-FableTurboMultilingualNeural4',
  'en-US-OnyxTurboMultilingualNeural4',
  'en-US-NovaTurboMultilingualNeural4',
  'en-US-ShimmerTurboMultilingualNeural4',
  'en-US-BrianMultilingualNeural4',
  'en-US-AvaNeural',
  'en-US-AndrewNeural',
  'en-US-EmmaNeural',
  'en-US-BrianNeural',
  'en-US-JennyNeural',
  'en-US-GuyNeural',
  'en-US-AriaNeural',
  'en-US-DavisNeural',
  'en-US-JaneNeural',
  'en-US-JasonNeural',
  'en-US-KaiNeural',
  'en-US-LunaNeural',
  'en-US-SaraNeural',
  'en-US-TonyNeural',
  'en-US-NancyNeural',
  'en-US-CoraMultilingualNeural4',
  'en-US-ChristopherMultilingualNeural4',
  'en-US-BrandonMultilingualNeural4',
  'en-US-AmberNeural',
  'en-US-AnaNeural',
  'en-US-AshleyNeural',
  'en-US-BrandonNeural',
  'en-US-ChristopherNeural',
  'en-US-CoraNeural',
  'en-US-ElizabethNeural',
  'en-US-EricNeural',
  'en-US-JacobNeural',
  'en-US-JennyMultilingualNeural4',
  'en-US-MichelleNeural',
  'en-US-MonicaNeural',
  'en-US-RogerNeural',
  'en-US-RyanMultilingualNeural4',
  'en-US-SteffanMultilingualNeural4',
  'en-US-SteffanNeural',
  'en-US-AdamMultilingualNeural1,4',
  'en-US-AIGenerate1Neural1',
  'en-US-AIGenerate2Neural1',
  'en-US-AmandaMultilingualNeural1,4',
  'en-US-AshTurboMultilingualNeural1,4',
  'en-US-BlueNeural1',
  'en-US-DavisMultilingualNeural1,4',
  'en-US-DerekMultilingualNeural1,4',
  'en-US-DustinMultilingualNeural1,4',
  'en-US-EvelynMultilingualNeural1,4',
  'en-US-LewisMultilingualNeural1,4',
  'en-US-LolaMultilingualNeural1,4',
  'en-US-NancyMultilingualNeural1,4',
  'en-US-PhoebeMultilingualNeural1,4',
  'en-US-SamuelMultilingualNeural1,4',
  'en-US-SerenaMultilingualNeural1,4',
  'en-US-Adam:DragonHDLatestNeural',
  'en-US-Andrew:DragonHDLatestNeural',
  'en-US-Andrew2:DragonHDLatestNeural',
  'en-US-Ava:DragonHDLatestNeural',
  'en-US-Brian:DragonHDLatestNeural',
  'en-US-Davis:DragonHDLatestNeural',
  'en-US-Emma:DragonHDLatestNeural',
  'en-US-Emma2:DragonHDLatestNeural',
  'en-US-Steffan:DragonHDLatestNeural',
  'en-US-Alloy:DragonHDLatestNeural1',
  'en-US-Andrew3:DragonHDLatestNeural1',
  'en-US-Aria:DragonHDLatestNeural1',
  'en-US-Ava3:DragonHDLatestNeural1',
  'en-US-Bree:DragonHDLatestNeural1',
  'en-US-Jane:DragonHDLatestNeural1',
  'en-US-Jenny:DragonHDLatestNeural1',
  'en-US-MultiTalker-Ava-Andrew:DragonHDLatestNeural1',
  'en-US-MultiTalker-Ava-Steffan:DragonHDLatestNeural1',
  'en-US-Nova:DragonHDLatestNeural1',
  'en-US-Phoebe:DragonHDLatestNeural1',
  'en-US-Serena:DragonHDLatestNeural1',
  'en-ZA-LeahNeural',
  'en-ZA-LukeNeural',
];