// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:vitalingu/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CEFRAdapter());
    registerAdapter(GrammarTopicAdapter());
    registerAdapter(GrammarTopicUserDataAdapter());
    registerAdapter(SupportedLanguagesBcp47Adapter());
    registerAdapter(UserLanguageSkillsDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CEFRAdapter());
    registerAdapter(GrammarTopicAdapter());
    registerAdapter(GrammarTopicUserDataAdapter());
    registerAdapter(SupportedLanguagesBcp47Adapter());
    registerAdapter(UserLanguageSkillsDataAdapter());
  }
}
